# Sample Tests

import unittest

# Generated by CodiumAI
from src.initial_1 import addFunction 


import pytest

class TestAddfunction:

    # Test with two positive integers
    def test_two_positive_integers(self):
        assert addFunction(2, 3) == 5

    # Test with two negative integers
    def test_two_negative_integers(self):
        assert addFunction(-2, -3) == -5

    # Test with one positive and one negative integer
    def test_positive_and_negative_integer(self):
        assert addFunction(2, -3) == -1

    # Test with two zeros
    def test_two_zeros(self):
        assert addFunction(0, 0) == 0

    # Test with two floating point numbers
    def test_two_floats(self):
        assert addFunction(2.5, 3.7) == 6.2

    # Test with non-integer inputs
    def test_non_integer_inputs(self):
        assert addFunction("2", 3) == "23"